# Generated by Django 4.2 on 2024-08-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facade', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTDLModelParsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtdl_id', models.CharField(max_length=255, unique=True)),
                ('specification', models.JSONField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'DTDL parsed model',
                'verbose_name_plural': 'DTDL parsed models',
            },
        ),
        migrations.CreateModel(
            name='SystemContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'System context',
                'verbose_name_plural': 'System contexts',
            },
        ),
        migrations.CreateModel(
            name='ModelRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('dtdl_parsed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_relationships', to='orchestrator.dtdlmodelparsed')),
            ],
            options={
                'verbose_name': 'Model relationship',
                'verbose_name_plural': 'Model relationships',
            },
        ),
        migrations.CreateModel(
            name='ModelElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.IntegerField()),
                ('element_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('schema', models.CharField(blank=True, max_length=50, null=True)),
                ('supplement_types', models.JSONField(blank=True, null=True)),
                ('dtdl_parsed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_elements', to='orchestrator.dtdlmodelparsed')),
            ],
            options={
                'verbose_name': 'Model element',
                'verbose_name_plural': 'Model elements',
            },
        ),
        migrations.AddField(
            model_name='dtdlmodelparsed',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.systemcontext'),
        ),
        migrations.CreateModel(
            name='DTDLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specification', models.JSONField()),
                ('parser_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dtdlparserclient')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.systemcontext')),
            ],
            options={
                'verbose_name': 'DTDL model',
                'verbose_name_plural': 'DTDL models',
            },
        ),
        migrations.CreateModel(
            name='DigitalTwinInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.dtdlmodelparsed')),
            ],
            options={
                'verbose_name': 'Digital twin instance',
                'verbose_name_plural': 'Digital twins instances',
            },
        ),
        migrations.CreateModel(
            name='DigitalTwinInstanceProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('device_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facade.property')),
                ('dtinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.digitaltwininstance')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.modelelement')),
            ],
            options={
                'verbose_name': 'Digital twin instance property',
                'verbose_name_plural': 'Digital twin instances properties',
                'unique_together': {('dtinstance', 'property', 'device_property')},
            },
        ),
    ]
