# Generated by Django 4.2 on 2024-07-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DTDLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtdl_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('dtdl_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_relationships', to='orchestrator.dtdlmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.IntegerField()),
                ('element_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('schema', models.CharField(blank=True, max_length=50, null=True)),
                ('supplement_types', models.JSONField(blank=True, null=True)),
                ('dtdl_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_elements', to='orchestrator.dtdlmodel')),
            ],
        ),
    ]
