# Generated by Django 4.2 on 2024-07-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_alter_device_unique_together'),
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwinInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.JSONField(default=dict)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facade.device')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.dtdlmodel')),
            ],
        ),
    ]
