# Generated by Django 5.1 on 2025-01-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='digitaltwininstancerelationship',
            unique_together={('source_instance', 'target_instance', 'relationship')},
        ),
    ]
