# Generated by Django 4.2 on 2024-07-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtdlmodelparsed',
            name='specification',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
