# Generated by Django 4.2 on 2024-07-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitaltwininstance',
            name='uuid',
        ),
    ]
