# Generated by Django 4.2 on 2024-07-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitaltwininstance',
            name='application',
        ),
        migrations.AddField(
            model_name='dtdlmodel',
            name='application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orchestrator.application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtdlmodelparsed',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orchestrator.application'),
            preserve_default=False,
        ),
    ]
