# Generated by Django 5.1 on 2025-02-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_alter_digitaltwininstancerelationship_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dtdlmodel',
            unique_together={('system', 'dtdl_id')},
        ),
    ]
