# Generated by Django 4.2 on 2024-07-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_remove_digitaltwininstance_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltwininstanceproperty',
            name='schema',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
