# Generated by Django 4.2 on 2024-07-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_alter_device_unique_together'),
        ('orchestrator', '0002_digitaltwininstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwinInstanceProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('device_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facade.property')),
                ('dtinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.digitaltwininstance')),
            ],
        ),
    ]
