# Generated by Django 4.2 on 2024-07-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_digitaltwininstanceproperty_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitaltwininstanceproperty',
            name='causal',
        ),
        migrations.AlterField(
            model_name='digitaltwininstanceproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orchestrator.modelelement'),
        ),
    ]
