# Generated by Django 4.2 on 2024-07-03 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_alter_device_unique_together'),
        ('orchestrator', '0003_digitaltwininstanceproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitaltwininstance',
            name='properties',
        ),
        migrations.AlterField(
            model_name='digitaltwininstanceproperty',
            name='device_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facade.property'),
        ),
    ]
