# Generated by Django 5.1 on 2025-02-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0003_alter_dtdlmodel_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelrelationship',
            unique_together={('dtdl_model', 'name', 'source', 'target')},
        ),
    ]
