# Generated by Django 5.1 on 2025-04-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0004_alter_modelrelationship_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltwininstance',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='digitaltwininstance',
            name='last_status_check',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
