# Generated by Django 4.2 on 2024-07-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_alter_device_unique_together'),
        ('orchestrator', '0004_remove_digitaltwininstance_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaltwininstanceproperty',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='digitaltwininstanceproperty',
            unique_together={('dtinstance', 'property', 'device_property')},
        ),
    ]
