# Generated by Django 4.2 on 2024-07-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_dtdlmodelparsed_especification'),
        ('orchestrator', '0004_remove_digitaltwininstanceproperty_causal_and_more'),
        ('orchestrator', '0005_alter_digitaltwininstanceproperty_value_and_more'),
    ]

    operations = [
    ]
