# Generated by Django 5.1 on 2025-06-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0005_digitaltwininstance_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaltwininstance',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
