# Generated by Django 5.1 on 2025-09-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0006_digitaltwininstance_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='digitaltwininstanceproperty',
            unique_together={('dtinstance', 'property')},
        ),
    ]
