services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nomebanco
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:sua_senha@db:5432/seu_banco

  neo4j:
    image: neo4j:5.8
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password

volumes:
  db_data:
