services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      test: ["CMD", "python", "manage.py", "check"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - static_volume:/middleware-dt/static

  neo4j:
    image: neo4j:5.8
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p $(echo ${NEO4J_AUTH} | cut -d/ -f1) -p $(echo ${NEO4J_AUTH} | cut -d/ -f2) -e 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - middleware
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - static_volume:/etc/nginx/staticfiles/static

  parser:
    image: andregustavoo/parserwebapi:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: always
    networks:
      - default

volumes:
  db_data:
  static_volume:
