# Generated by Django 5.1 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_gatewayiot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewayiot',
            name='api_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='gatewayiot',
            name='auth_method',
            field=models.CharField(
                choices=[('user_password', 'Usuario e senha'), ('api_key', 'API Key')],
                default='user_password',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='gatewayiot',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gatewayiot',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
