# Generated by Django 4.2 on 2024-07-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rpc_read_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='rpc_write_method',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
