# Generated by Django 4.2 on 2024-07-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Boolean', 'Boolean'), ('Integer', 'Integer'), ('Double', 'Double')])),
                ('causal', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facade.device')),
            ],
            options={
                'unique_together': {('device', 'name')},
            },
        ),
    ]
