# Generated by Django 5.1 on 2025-04-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='inactivityTimeout',
            field=models.IntegerField(blank=True, help_text="Timeout in seconds for device inactivity. Overrides type's timeout", null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='inactivityTimeout',
            field=models.IntegerField(blank=True, help_text='Timeout in seconds for device inactivity', null=True),
        ),
    ]
