# Generated by Django 4.2 on 2024-07-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_property_rpc_read_method_property_rpc_write_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
