# Generated by Django 5.1 on 2025-06-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_device_inactivitytimeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='metadata',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='inactivityTimeout',
            field=models.IntegerField(blank=True, default=60, help_text='Timeout in seconds for device inactivity', null=True),
        ),
    ]
