# Generated by Django 4.2 on 2024-07-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_remove_device_device_id_property'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('identifier', 'gateway')},
        ),
    ]
