# Generated by Django 4.2 on 2024-07-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_alter_device_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='rpc_methods',
        ),
        migrations.RemoveField(
            model_name='property',
            name='causal',
        ),
    ]
