# Generated by Django 4.2 on 2024-07-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_alter_property_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rpc_read_method',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='rpc_write_method',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
