# Generated by Django 4.2 on 2024-07-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0004_alter_property_rpc_read_method_and_more'),
        ('facade', '0004_remove_devicetype_rpc_methods_remove_property_causal'),
    ]

    operations = [
    ]
